// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type File struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	URL  string `json:"url"`
}

type Mutation struct {
}

type Query struct {
}
